### ISSUE TITLE
Non-ranked plays don't always show up in recent plays

### ISSUE THREAD

**Issue by peppy** [ppy/osu-queue-score-statistics#209]
Currently working around via https://github.com/ppy/osu-queue-score-statistics/pull/208.

```
 ---> System.AggregateException: Processing legacy score 24070127164 failed. (Total score conversion operation returned invalid total of -9223372036854775808)
 import-scores-osu-6bb5484df-k9wtp  ---> System.InvalidOperationException: Total score conversion operation returned invalid total of -9223372036854775808 
 import-scores-osu-6bb5484df-k9wtp at osu.Game.Database.StandardisedScoreMigrationTools.convertFromLegacyTotalScore(ScoreInfo score, Ruleset ruleset, LegacyBeatmapConversionDifficultyInfo difficulty, LegacyScoreAttributes attributes)  
at osu.Server.Queues.ScoreStatisticsProcessor.Commands.Queue.BatchInserter.CreateReferenceScore(Int32 rulesetId, HighScore highScore) in /app/Commands/Queue/BatchInserter.cs:line 225
import-scores-osu-6bb5484df-k9wtp at osu.Server.Queues.ScoreStatisticsProcessor.Commands.Queue.BatchInserter.<>c__DisplayClass21_0.<run>b__0(HighScore highScore) in /app/Commands/Queue/BatchInserter.cs:line 133
import-scores-osu-6bb5484df-k9wtp --- End of inner exception stack trace ---   

at osu.Server.Queues.ScoreStatisticsProcessor.Commands.Queue.BatchInserter.<>c__DisplayClass21_0.<run>b__0(HighScore highScore) in /app/Commands/Queue/BatchInserter.cs:line 167
import-scores-osu-6bb5484df-k9wtp at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
import-scores-osu-6bb5484df-k9wtp at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

--- End of stack trace from previous location ---
import-scores-osu-6bb5484df-k9wtp at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
import-scores-osu-6bb5484df-k9wtp at System.Threading.Tasks.TaskReplicator.Replica.Execute()

--- End of inner exception stack trace ---
```

**Comment by bdach** [comment]
https://discord.com/channels/188630481301012481/188630616286167041/1202237255574618272 may also be related

**Comment by peppy** [comment]
This was brought up on discord as basically "any score set against a non-ranked beatmap will not show in recent scores anymore". I think we probably want to fix this as a priority, and I can think of two ways forward:

- We allow the insert to go ahead with either a zero `TotalScore` (but all the legacy info populated correctly)
- We process scoring attribs for all pending/graveyarded beatmaps to date

The second seems like a more sustainable way forward, but may have caching considerations (currently the score watcher has a limited memory footprint by the number of ranked beatmaps).

@bdach any thoughts on this?

**Comment by peppy** [comment]
I'm populating statistics for all beatmaps to see how things go.

**Comment by bdach** [comment]
I suppose my thoughts are not really that relevant at this stage if the scoring statistics are being populated are they.

**Comment by peppy** [comment]
This is now fixed from my end, can confirm all plays are importing correctly now.
