### ISSUE TITLE
High score importer doesn't set `started_at`

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-queue-score-statistics#40]
Pumping scores imported via the high score importer fails with:
```
Error processing score_id: 32479 user_id: 161270: System.AggregateException: One or more errors occurred. (Nullable object must have a value.)
 ---> System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at osu.Server.Queues.ScoreStatisticsProcessor.Processors.PlayCountProcessor.adjustMonthlyPlaycount(SoloScoreInfo score, MySqlConnection conn, MySqlTransaction transaction, Boolean revert) in /home/smgi/Repos/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs:line 53
   at osu.Server.Queues.ScoreStatisticsProcessor.Processors.PlayCountProcessor.ApplyToUserStats(SoloScoreInfo score, UserStats userStats, MySqlConnection conn, MySqlTransaction transaction) in /home/smgi/Repos/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs:line 32
   at osu.Server.Queues.ScoreStatisticsProcessor.ScoreStatisticsProcessor.ProcessResult(ScoreItem item) in /home/smgi/Repos/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/ScoreStatisticsProcessor.cs:line 86
   at osu.Server.QueueProcessor.QueueProcessor`1.ProcessResults(IEnumerable`1 items)
   at osu.Server.QueueProcessor.QueueProcessor`1.<>c__DisplayClass21_0.<Run>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
```
Because the `PlayCountProcessor` and `PlayTimeProcessor` expect `started_at` and/or `ended_at` to be non-null:
https://github.com/ppy/osu-queue-score-statistics/blob/5be36d71d04662409c93db2453a8c5fb0da8473c/osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayCountProcessor.cs#L51-L60
https://github.com/ppy/osu-queue-score-statistics/blob/5be36d71d04662409c93db2453a8c5fb0da8473c/osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs#L28-L34
https://github.com/ppy/osu-queue-score-statistics/blob/5be36d71d04662409c93db2453a8c5fb0da8473c/osu.Server.Queues.ScoreStatisticsProcessor/Processors/PlayTimeProcessor.cs#L40-L60

**Comment by smoogipoo** [comment]
I'm not sure what `started_at` and `ended_at` should be set to for these case. Highscores have a `date` - perhaps that should be set as `ended_at`, and `started_at` be `ended_at - beatmap_length`?

**Comment by peppy** [comment]
Sounds okay for now

**Comment by peppy** [comment]
Actually I'd leave `started_at` empty and fix the commands to handle that (since we really don't know the `started_at` time).

**Comment by smoogipoo** [comment]
So how should `start_time` be handled then?

- Make `PlayCountProcessor` update based on `ended_at`.
- Make `PlayTimeProcessor` use the beatmap length.

Does that fit your expectations?

**Comment by peppy** [comment]
`PlayCount` should use `started_at??ended_at`

`PlayTime` should mostly already fallback to the beatmap length, all going well.
