### ISSUE TITLE
High score importer cannot be run a second time after the most recent changes

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-queue-score-statistics#42]
Previously, if you called `import-high-scores` with pre-existing scores, it would skip them.

As of https://github.com/ppy/osu-queue-score-statistics/pull/39, this has broken, and now throws a duplicate primary key exception:
```
/home/smgi/Repos/osu-queue-score-statistics/osu.Server.Queues.ScorePump/bin/Debug/net6.0/osu.Server.Queues.ScorePump import-high-scores
Increasing processing rate to 2100 due to latency of 0
Retrieving next 2100 scores from 0
Inserting up to 12,071,481 [0 /5] 0 inserted (+0 new 0/s)
ERROR: At least one tasks were faulted.
ERROR: System.AggregateException: One or more errors occurred. (Duplicate entry '0-9620368' for key 'solo_scores_legacy_id_map.PRIMARY')
 ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry '0-9620368' for key 'solo_scores_legacy_id_map.PRIMARY'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 958
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 129
   at MySqlConnector.MySqlDataReader.NextResultAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 81
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 467
```

As an aside, this exception also doesn't seem to crash the program and just leaves it hanging endlessly using 0% CPU...

**Comment by peppy** [comment]
Can you check why it's not crashing? It rightfully does for me:

```
root@es-scores-staging:~/osu-queue-score-statistics# docker run --network="host" -it -e "elasticsearch_host=http://localhost:9200" -e "REDIS_HOST=localhost" -e "DB_HOST=db" -e "DB_USER=next" $(docker build . -q -f ./osu.Server.Queues.ScorePump/Docker
file) import-high-scores -r0 -s 4073664647                                                                                   Increasing processing rate to 2100 due to latency of 0
Retrieving next 2100 scores from 4073664647
Inserting up to 4,073,667,875 [0 /5] 0 inserted (+0 new 0/s)
ERROR: At least one tasks were faulted.                                                                                      ERROR: System.AggregateException: One or more errors occurred. (Duplicate entry '0-4073665287' for key 'test_solo_scores_lega
cy_id_map.PRIMARY')                                                                                                           ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry '0-4073665287' for key 'test_solo_scores_legacy_id_map.PRIM
ARY'
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSessio
n.cs:line 958
```

**Comment by peppy** [comment]
Also, the previous version "skipping" was just by luck (exceptions were being silenced but still happening). I'm not against adding a mode where it skips existing, but it should be defined as an explicit mode. This import process also does not handle other cases for re-runs, such as deleted entries, and is not intended to be used in such a manner.

**Comment by smoogipoo** [comment]
Hmm... Sometimes it does end the process, sometimes it doesn't... Around 80% of the time it doesn't. Maybe something linux-specific...

That's fair enough, just means if anything goes wrong during the process you basically have to restart the entire thing. Like I just caused too many mysql connections and boom :sweat_smile:

**Comment by peppy** [comment]
In theory you should not need to restart the entire thing. It is transactionally consistent and you can resume from the last import ID safely.

**Comment by smoogipoo** [comment]
Will close this for now then.
